// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_5Q7u7eF5RphEGddoXJiQsskRxDW3QE',
    appId: '1:302703857980:web:eae8d1269a5ed194b40e39',
    messagingSenderId: '302703857980',
    projectId: 'booksrack-6ed2e',
    authDomain: 'booksrack-6ed2e.firebaseapp.com',
    storageBucket: 'booksrack-6ed2e.appspot.com',
    measurementId: 'G-KDSWJ5JK0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbWI6vRT2JWkUpU5wIBXOZ1CaZMZs_12c',
    appId: '1:302703857980:android:d6964c712f2290a2b40e39',
    messagingSenderId: '302703857980',
    projectId: 'booksrack-6ed2e',
    storageBucket: 'booksrack-6ed2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKHTBvPGnc7EjqF5uXEahuEGhWrBN6nek',
    appId: '1:302703857980:ios:35cf11117863c185b40e39',
    messagingSenderId: '302703857980',
    projectId: 'booksrack-6ed2e',
    storageBucket: 'booksrack-6ed2e.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKHTBvPGnc7EjqF5uXEahuEGhWrBN6nek',
    appId: '1:302703857980:ios:35cf11117863c185b40e39',
    messagingSenderId: '302703857980',
    projectId: 'booksrack-6ed2e',
    storageBucket: 'booksrack-6ed2e.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5_5Q7u7eF5RphEGddoXJiQsskRxDW3QE',
    appId: '1:302703857980:web:c158e5076b686f60b40e39',
    messagingSenderId: '302703857980',
    projectId: 'booksrack-6ed2e',
    authDomain: 'booksrack-6ed2e.firebaseapp.com',
    storageBucket: 'booksrack-6ed2e.appspot.com',
    measurementId: 'G-DRDKQX7KLC',
  );
}
